title: Michelle Liang
title_logo_light: /assets/homepage/title.png
title_logo_dark: /assets/homepage/titledark.png
logo: /assets/homepage/logo.gif
description: Thanks for visiting my personal website!
theme: jekyll-theme-minimal
url: https://michliang.github.io
plugins:
  - jekyll-sitemap
defaults:
  - scope:
      path: ''
    values:
      image: /assets/homepage/ogo.png
