title: Michelle Liang
title_logo: /assets/homepage/title.png
logo: /assets/homepage/logo.gif
description: Thanks for visiting my personal website!
theme: jekyll-theme-minimal
url: https://michliang.github.io
plugins:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"
      image: /assets/homepage/ogo.png