title: Michelle Liang
title_logo: /assets/homepage/title.png
logo: /assets/homepage/logo.gif
description: Thanks for visiting my personal website!
theme: jekyll-theme-minimal
url: https://michliang.github.io
relative_permalinks: false
plugins:
  - jekyll-sitemap
