# TODO: Include menu
menu:
- {name: 'About me', path: 'menu', url: 'about.html'}
- {name: 'Art Portfolio', path: 'menu', url: 'portfolio.html'}
- {name: 'Notes', path: 'menu', url: 'notes.html'}
- {name: 'Design Commissions', path: 'commissions', url: 'commissions.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: '<i class="fab fa-github"></i>', link: 'https://github.com/MichLiang'}
- {icon: '<i class="fab fa-linkedin"></i>', link: 'http://www.linkedin.com/in/michelleliangpharmd/'}
- {icon: '<i class="fab fa-instagram"></i>', link: 'https://www.instagram.com/michelleliangx/'}
- {icon: '<i class="fas fa-envelope"></i>', link: 'mailto:michelleliangx@gmail.com'}
- {icon: '<i class="fab fa-twitter"></i>', link: 'https://twitter.com/michellelianguw?lang=en'}
