menu:
- {name: 'Home'}
- {name: 'About', url: 'about.html'}
- {name: 'Notes', url: 'notes.html'}
- {name: 'Art Portfolio', url: 'portfolio.html'}
- {name: 'Musings', url: 'musings.html'}
- {name: 'Side Projects', url: 'sideprojects.html'}

social:
- {icon: 'fab fa-github fa-2x', link: 'https://github.com/MichLiang'}
- {icon: 'fab fa-linkedin fa-2x', link: 'http://www.linkedin.com/in/michelleliangpharmd/'} 
- {icon: 'fab fa-instagram fa-2x', link: 'https://www.instagram.com/michelleliangkoh/'} 
- {icon: 'fas fa-envelope fa-2x', link: 'mailto:michelleliangx@gmail.com'} 
- {icon: 'fab fa-twitter fa-2x', link: 'https://twitter.com/michellelianguw'} 
