# TODO: Include menu
menu:
- {name: 'About me', path: 'menu', url: 'about.html'}
- {name: 'Art Portfolio', path: 'menu', url: 'portfolio.html'}
- {name: 'Notes', path: 'menu', url: 'notes.html'}
- {name: 'Design Commissions', path: 'commissions', url: 'commissions.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'fab fa-github fa-lg', link: 'https://github.com/MichLiang'}
- {icon: 'fab fa-linkedin fa-lg', link: 'http://www.linkedin.com/in/michelleliangpharmd/'}
- {icon: 'fab fa-instagram fa-lg', link: 'https://www.instagram.com/michelleliangx/'}
- {icon: 'fas fa-envelope fa-lg', link: 'mailto:michelleliangx@gmail.com'}
- {icon: 'fab fa-twitter fa-lg', link: 'https://twitter.com/michellelianguw?lang=en'}
